apiVersion: v1
kind: Pod
metadata:
  name: iperf-service-pod
  annotations:
    v1.multus-cni.io/default-network: accelerated
  labels:
    app: iperf3-pod-service
spec:
  nodeSelector:
    kubernetes.io/hostname: l-cloudx6-03
  containers:
  - name: appcntr1
    image: harbor.mellanox.com/cloud-orchestration-dev/hw-offload-test
    command: ['/bin/sh', '-c', 'iperf3 -s']
    resources:
      requests:
        mellanox.com/mlnx_cx6dx: '1'
      limits:
        mellanox.com/mlnx_cx6dx: '1'
