apiVersion: v1
kind: Pod
metadata:
  name: regular-pod-cloudx6-08
  annotations:
    v1.multus-cni.io/default-network: accelerated
spec:
  nodeSelector:
    kubernetes.io/hostname: l-cloudx6-08
  containers:
  - name: appcntr1
    image: harbor.mellanox.com/cloud-orchestration-dev/hw-offload-test
    command: ['/bin/sh', '-c', 'sleep infinity']
    resources:
      requests:
        mellanox.com/mlnx_cx6dx: '1'
      limits:
        mellanox.com/mlnx_cx6dx: '1'
